package redhat.sample.com.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-07-13T20:05:17.520+02:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://com.sample.redhat/ws", name = "echo")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Echo {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://com.sample.redhat/ws", partName = "return")
    public java.lang.String echo(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
